[project]
name = "ticktask"
version = "0.1.0"
description = "Pomodoro-style terminal task manager"
readme = "README.md"
authors = [
    { name = "Marco Ramos", email = "ticktask@marcoramos.me" }
]
requires-python = ">=3.13"
dependencies = [
    "platformdirs>=4.5.0",
    "pillow>=11.3.0",
    "pystray>=0.19.5",
    "sqlalchemy>=2.0.48",
    "textual>=6.8.0",
]

[project.scripts]
ticktask = "ticktask.main:main"

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.20.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.10",
]

[tool.ruff]
include = [
    "src/**/*.py",
    "tests/**/*.py"
]

[tool.mypy]
python_version = "3.13"
files = ["src"]
mypy_path = "src"
explicit_package_bases = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
warn_redundant_castes = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
    "pystray.*"
]

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs=false
check_untyped_defs=false
warn_return_any = false
no_implicit_reexport = false

[tool.pytest.ini_options]
addopts = [
    "--verbose",
    "--cov=ticktask",
    "--cov-branch",
    "--cov-report=term-missing",
    "--cov-fail-under=60"
]
testpaths = ["tests"]

[tool.coverage.run]
source = ["ticktask"]
omit = ["tests/*", "**/__init__.py"]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 60
exclude_lines = [
    "pragma: no cover",
    "@abc.abstractmethod",
    "raise NotImplementedError",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
